#! /bin/bash

git_toplevel="$(git rev-parse --show-toplevel)"
note_directory="${git_toplevel}/session-notes"
script_directory="${note_directory}/cleanup-notes"
script_path="${script_directory}/cleanup_session_notes.py"

cd  "${note_directory}" || exit 2



for arg in "$@"
do
    if [[ ! -f "$arg" ]]; then
	date="$arg"
	filename="session-notes-${date}.md"
    else
	filename="$arg"
    fi

    . "${script_directory}/venv/bin/activate" || exit 3

    python "${script_path}" "${filename}"
done

