#! /bin/bash

git_toplevel="$(git rev-parse --show-toplevel)"
note_directory="${git_toplevel}/session-notes"
script_directory="${git_toplevel}/src/session_notes_cleanup"
script_path="${script_directory}/session_notes_cleaner.py"


for arg in "$@"
do
    if [[ ! -f "$arg" ]]; then
	date="$arg"
	filename="session-notes-${date}.md"
    else
	filename="$arg"
    fi

    # . "${git_toplevel}/venv/bin/activate" || exit 3

    python "${script_path}" "${filename}"
done

